language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --dev
  - cp phpunit.xml.dist phpunit.xml

script:
  - phpunit

notifications:
  email: false
